### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [KeithSloan/toSketch#1]
Something in the latest update causes problems with selecting a face and clicking tosketch, it says that a face has no len.

**Comment by KeithSloan** [comment]
Are you able to provide the message in Report View that says face has no len? i.e. a Line number would be useful. Thanks

**Comment by infosisio** [comment]
```
10:36:40  Running the Python command 'toSketchCommand' failed:
Traceback (most recent call last):
  File ".FreeCAD/Mod/toSketch/freecad/toSketch/toSCommands.py", line 56, in Activated
    sketch = self.shapes2Sketch(face,'Sketch')
  File ".FreeCAD/Mod/toSketch/freecad/toSketch/toSCommands.py", line 173, in shapes2Sketch
    print(len(shapes))

object of type 'Part.Face' has no len()
```

**Comment by KeithSloan** [comment]
Have removed the print statement on line 173 as it was just informative

shape2Sketch invokes Draft.makesSketch and hopefully works with your Face

Try latest version and thanks for reporting

**Comment by KeithSloan** [comment]
Should now be fixed

**Comment by Apfelwurm** [comment]
Seems like i get the same error on the current version:
```
19:51:42  Selected-Ex BaseFeature Gui::SelectionObject
19:51:42  SubObjects
19:51:42  Planar
19:51:42  Running the Python command 'toSketchCommand' failed:
Traceback (most recent call last):
  File "/home/user/.local/share/FreeCAD/Mod/toSketch/./freecad/toSketch/toSCommands.py", line 55, in Activated
    sketch = self.shapes2Sketch(face,'Sketch')
  File "/home/user/.local/share/FreeCAD/Mod/toSketch/./freecad/toSketch/toSCommands.py", line 191, in shapes2Sketch
    print(f'shapes2sketch {name}{len(shapes)}')

object of type 'Part.Face' has no len()
```

have a nice day!

**Comment by KeithSloan** [comment]
Please could you supply a FreeCAD file and info on which Face you are selecting.

**Comment by Apfelwurm** [comment]
Sure! The File i use is this one: https://files.volzit.de/share/E_gQwLka and the screenshot of the selected face is here: https://files.volzit.de/share/CI6FSAKf the selection in the console states 
``` Gui.Selection.addSelection('testcomplete','Body','BaseFeature.Face153',0.253249,2.89719,0)``` 

Thank you :)

**Comment by KeithSloan** [comment]
Thanks for reporting and please try latest version.

**Comment by Apfelwurm** [comment]
Works now, thank you!
